language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs-v2.0.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - "npm update -g npm"
after_success:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
